//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warpspeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.WUsers = new HashSet<WUser>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<WUser> WUsers { get; set; }
    }
}
