//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warpspeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public NotificationType()
        {
            this.ProjectNotifications = new HashSet<ProjectNotification>();
            this.SubProjectNotifcations = new HashSet<SubProjectNotifcation>();
            this.TaskNotifcations = new HashSet<TaskNotifcation>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ProjectNotification> ProjectNotifications { get; set; }
        public virtual ICollection<SubProjectNotifcation> SubProjectNotifcations { get; set; }
        public virtual ICollection<TaskNotifcation> TaskNotifcations { get; set; }
    }
}
