//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warpspeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSeen
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> WUserID { get; set; }
        public Nullable<System.Guid> TaskNotificationID { get; set; }
        public Nullable<System.Guid> ProjectNotificationID { get; set; }
        public Nullable<System.Guid> SubProjectNotificationID { get; set; }
    
        public virtual ProjectNotification ProjectNotification { get; set; }
        public virtual SubProjectNotifcation SubProjectNotifcation { get; set; }
        public virtual TaskNotifcation TaskNotifcation { get; set; }
        public virtual WUser WUser { get; set; }
    }
}
