//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warpspeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProject
    {
        public SubProject()
        {
            this.SubProjectNotifcations = new HashSet<SubProjectNotifcation>();
            this.Tasks = new HashSet<Task>();
            this.WUserSubprojects = new HashSet<WUserSubproject>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedID { get; set; }
        public Nullable<int> PercentComplete { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual WUser WUser { get; set; }
        public virtual ICollection<SubProjectNotifcation> SubProjectNotifcations { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<WUserSubproject> WUserSubprojects { get; set; }
    }
}
