//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warpspeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WUser
    {
        public WUser()
        {
            this.NotificationSeens = new HashSet<NotificationSeen>();
            this.Projects = new HashSet<Project>();
            this.ProjectNotifications = new HashSet<ProjectNotification>();
            this.SubProjects = new HashSet<SubProject>();
            this.SubProjectNotifcations = new HashSet<SubProjectNotifcation>();
            this.Tasks = new HashSet<Task>();
            this.TaskNotifcations = new HashSet<TaskNotifcation>();
            this.WUserProjects = new HashSet<WUserProject>();
            this.WUserSubprojects = new HashSet<WUserSubproject>();
            this.Groups = new HashSet<Group>();
        }
    
        public System.Guid ID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<System.Guid> EmailCode { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }
    
        public virtual ICollection<NotificationSeen> NotificationSeens { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectNotification> ProjectNotifications { get; set; }
        public virtual ICollection<SubProject> SubProjects { get; set; }
        public virtual ICollection<SubProjectNotifcation> SubProjectNotifcations { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskNotifcation> TaskNotifcations { get; set; }
        public virtual ICollection<WUserProject> WUserProjects { get; set; }
        public virtual ICollection<WUserSubproject> WUserSubprojects { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
